############################################################################
# Copyright (c) 2025 Renesas Electronics Corporation and/or its affiliates
#
# SPDX-License-Identifier: BSD-3-Clause
############################################################################

############################################################################
# Board specific toolchain and include configuration for Renesas RZ/V2H
############################################################################

get_filename_component(RZV_WORKSPACE_ROOT "${PX4_SOURCE_DIR}/.." ABSOLUTE)

if(NOT DEFINED RZV_MAVLINK_USE_OPENAMP)
    set(RZV_MAVLINK_USE_OPENAMP OFF)
endif()

if(RZV_MAVLINK_USE_OPENAMP)
    add_definitions(-DRZV_MAVLINK_USE_OPENAMP=1)
else()
    add_definitions(-DRZV_MAVLINK_USE_OPENAMP=0)
endif()

set(RZV_INCLUDE_DIRS
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/inc
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/inc/api
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/inc/instances
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/src/bsp/mcu/all
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/src/bsp/mcu/rzv2h
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/src/rm_freertos_port
    ${RZV_WORKSPACE_ROOT}/rzv/fsp/src/rm_freertos_port/cr
    ${RZV_WORKSPACE_ROOT}/rzv_cfg/fsp_cfg
    ${RZV_WORKSPACE_ROOT}/rzv_cfg/fsp_cfg/bsp
    ${RZV_WORKSPACE_ROOT}/rzv_cfg/aws
    ${RZV_WORKSPACE_ROOT}/rzv_gen
    ${RZV_WORKSPACE_ROOT}/rzv/aws/FreeRTOS/FreeRTOS/Source/include
    ${RZV_WORKSPACE_ROOT}/rzv/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-Common/include
    # B1: platform FreeRTOS+POSIX shim (freertos-port); subpaths identical to the old in-repo copy.
    ${RZV_WORKSPACE_ROOT}/src/freertos_posix/include
    ${RZV_WORKSPACE_ROOT}/src/freertos_posix/include/portable
    ${RZV_WORKSPACE_ROOT}/src/freertos_posix/include/FreeRTOS_POSIX
    ${RZV_WORKSPACE_ROOT}/src/freertos_posix/include/private
    ${RZV_WORKSPACE_ROOT}/src/freertos_posix/portable
    ${RZV_WORKSPACE_ROOT}/src/freertos_posix/portable/include
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/board
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/hal
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/hal/drivers/rzv_fsp/include
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/services
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/shim
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/shim/px4
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/shim/px4/sys
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/shim/freertos
    ${PX4_SOURCE_DIR}/boards/renesas/rzv/src/storage/include
    ${RZV_WORKSPACE_ROOT}/src
    ${RZV_WORKSPACE_ROOT}/src/runtime
    ${RZV_WORKSPACE_ROOT}/src/soc_platform
    ${RZV_WORKSPACE_ROOT}/src/rpc
    ${RZV_WORKSPACE_ROOT}/src/tools
)

include_directories(SYSTEM ${RZV_INCLUDE_DIRS})

add_definitions(-D__PX4_FREERTOS)
add_definitions(-U__CUSTOM_FILE_IO__)
add_definitions(-DposixconfigENABLE_PTHREAD_MUTEX_T=1)
add_definitions(-DposixconfigENABLE_PTHREAD_COND_T=1)
add_definitions(-DposixconfigENABLE_PTHREAD_MUTEXATTR_T=1)
add_definitions(-DposixconfigENABLE_PTHREAD_CONDATTR_T=1)
add_definitions(-D__LINUX_ERRNO_EXTENSIONS__=1)
add_definitions(-D_POSIX_C_SOURCE=200809L)
add_definitions(-D_XOPEN_SOURCE=700)
add_definitions(-DCONFIG_RZV_FSP=1)
add_compile_definitions(
    # Only errno codes NOT already defined in FreeRTOS POSIX errno.h
    # Network errno codes
    EAFNOSUPPORT=106
    EADDRINUSE=112
    EADDRNOTAVAIL=125
    EALREADY=120
    EDESTADDRREQ=121
    ENETDOWN=115
    ENETUNREACH=114
    ENETRESET=126
    ENOBUFS=105
    ENOPROTOOPT=92
    ENOTSOCK=88
    EOPNOTSUPP=95
    EPROTO=71
    EPROTONOSUPPORT=123
    EPROTOTYPE=107
    # POSIX thread errno codes
    ECANCELED=140
    EOWNERDEAD=142
    ENOTRECOVERABLE=131
    # IPC errno codes
    EBADMSG=74
    EIDRM=43
    ENOMSG=42
    ENOLINK=67
    ENOSR=63
    ENOSTR=60
    ETIME=62
    # File system errno codes
    ENOLCK=37
    ELOOP=40
    # Aliases
    EWOULDBLOCK=EAGAIN
)

# Note: ENOTSUP is kept for backwards compatibility but duplicates EOPNOTSUPP
add_definitions(-DENOTSUP=95)

add_compile_options(-fstack-usage)

add_compile_options(-Wno-error=strict-prototypes)

# Force-include FreeRTOSCustomConfig.h before visibility.h so that
# configUSE_POSIX_ERRNO=1 is defined when FreeRTOS_POSIX/errno.h runs its
# #undef errno block.  Without this, FreeRTOSConfig.h (generated by FSP) does
# not set configUSE_POSIX_ERRNO, so errno gets undefined and C++ stdlib headers
# (ext/string_conversions.h) fail with "errno was not declared in this scope".
add_compile_options("SHELL:-include ${RZV_WORKSPACE_ROOT}/src/freertos_posix/FreeRTOSCustomConfig.h")

set(CONFIG_BOARD_DISABLE_PX4_DAEMON TRUE)
set(CONFIG_BOARD_DISABLE_SERIAL TRUE)
set(ENABLE_LOCKSTEP_SCHEDULER OFF CACHE BOOL "" FORCE)

# Tell component_information to embed mftp:// URIs instead of S3 URLs.
# Without this, component_general.json references S3 which doesn't have our
# custom board → QGC can't fetch actuators.json.xz → Actuators tab never shows.
# These files are served from firmware ROM by embedded_metadata.cpp.
set(config_romfs_extra_dependencies parameters_xml events_json actuators_json)
