# PX4 toolchain shim for Renesas RZ/V FreeRTOS+POSIX build

get_filename_component(_WORKSPACE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." REALPATH)
include("${_WORKSPACE_ROOT}/cross.cmake")

if(NOT DEFINED GNUARM_TOOLCHAIN_ROOT AND DEFINED ENV{GNUARM_TOOLCHAIN_ROOT})
    set(GNUARM_TOOLCHAIN_ROOT $ENV{GNUARM_TOOLCHAIN_ROOT})
endif()

if(NOT DEFINED GNUARM_TOOLCHAIN_ROOT AND DEFINED GNUARMEMB_TOOLCHAIN_PATH)
    set(GNUARM_TOOLCHAIN_ROOT "${GNUARMEMB_TOOLCHAIN_PATH}")
endif()

if(NOT DEFINED GNUARM_TOOLCHAIN_ROOT)
    set(GNUARM_TOOLCHAIN_ROOT "/opt/toolchains/gcc_arm/13_3-Rel1/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi")
endif()

set(GNUARM_TOOLCHAIN_ROOT "${GNUARM_TOOLCHAIN_ROOT}" CACHE PATH "GNU Arm Embedded toolchain root" FORCE)
set(GNUARMEMB_TOOLCHAIN_PATH "${GNUARM_TOOLCHAIN_ROOT}" CACHE PATH "GNU Arm Embedded toolchain" FORCE)
